kind: pipeline
type: docker
name: 盘古Drone插件


clone:
  disable: true


trigger:
  event:
    exclude:
      - pull_request


steps:
  - name: 拉代码
    image: dronestock/git
    pull: if-not-exists

  - name: 编译
    image: storezhang/pangu
    pull: if-not-exists
    settings:
      output: pangu

  - name: 打包Docker并推送
    image: plugins/docker
    pull: if-not-exists
    when:
      branch:
        - develop
        - master
    settings:
      repo: dronestock/pangu
      tags:
        - latest
      compress: true
      squash: true
      mirror: https://mirror.ccs.tencentyun.com
      username: dronestock
      password:
        from_secret: token_docker_dronestock
