kind: pipeline
type: docker
name: Drone插件


clone:
  disable: true


trigger:
  event:
    exclude:
      - pull_request


steps:
  - name: 拉代码
    image: ccr.ccs.tencentyun.com/dronestock/git
    pull: always
    settings:
      verbose: true
      debug: true
      ssk_key:
        from_secret: ssh_key_github

  - name: 编译
    image: dronestock/pangu
    pull: if-not-exists
    settings:
      verbose: true
      debug: true
      output: drone

  - name: 推送Docker镜像到中央库
    image: ccr.ccs.tencentyun.com/dronestock/docker
    pull: if-not-exists
    failure: ignore
    privileged: true
    settings:
      repository: dronestock/pangu
      username:
        from_secret: username_docker
      password:
        from_secret: token_docker
