kind: pipeline
type: docker
name: 盘古Drone插件


clone:
  disable: true


trigger:
  event:
    exclude:
      - pull_request


steps:
  - name: 拉代码
    image: storezhang/git
    pull: always

  - name: 编译
    image: storezhang/pangu
    pull: if-not-exists
    settings:
      output: pangu

  - name: 打包Docker并推送
    image: plugins/docker
    pull: if-not-exists
    when:
      branch:
        - develop
        - master
    settings:
      repo: storezhang/drone
      tags:
        - latest
      compress: true
      squash: true
      mirror: https://mirror.ccs.tencentyun.com,https://4lch7u25.mirror.aliyuncs.com,https://docker.mirrors.ustc.edu.cn,https://registry.docker-cn.com,https://hub-mirror.c.163.com
      username: storezhang
      password:
        from_secret: token_docker
