kind: pipeline
type: docker
name: Drone插件


clone:
  disable: true


steps:
  - name: 代码
    image: ccr.ccs.tencentyun.com/dronestock/git

  - name: 编译
    image: ccr.ccs.tencentyun.com/pangum/drone
    volumes:
      - name: go
        path: /var/lib/go
    settings:
      output:
        name: drone

  - name: 发布
    image: ccr.ccs.tencentyun.com/dronestock/docker
    privileged: true
    volumes:
      - name: docker
        path: /var/lib/docker
    environment:
      PASSWORD_DOCKER:
        from_secret: token_docker_pangum
      PASSWORD_CCR:
        from_secret: password_tencentyun_ccr
    settings:
      repository: pangum/drone
      registries:
        - username: pangum
          password: $${PASSWORD_DOCKER}
        - hostname: ccr.ccs.tencentyun.com
          username: "160290688"
          password: $${PASSWORD_CCR}
          required: true


volumes:
  - name: docker
    host:
      path: /var/lib/cache/docker
  - name: go
    host:
      path: /var/lib/cache/go
