kind: pipeline
type: docker
name: Drone插件


clone:
  disable: true


trigger:
  event:
    exclude:
      - pull_request


steps:
  - name: 拉代码
    image: dronestock/git
    pull: always

  - name: 编译
    image: pangum/drone
    pull: always
    settings:
      output: drone

  - name: 推送Docker镜像到中央库
    image: dronestock/docker
    pull: always
    privileged: true
    when:
      event:
        - tag
    volumes:
      - name: cache
        path: /var/lib/docker
    settings:
      repository: pangum/drone
      username: pangum
      password:
        from_secret: token_docker_pangum


volumes:
  - name: cache
    host:
      path: /var/lib/cache/docker
